# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\renne\Desktop\Python\Agendamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1335, 929)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(720, 290, 461, 91))
        self.frame.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"border-bottom:5px solid white;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 30, 371, 41))
        self.label.setStyleSheet("*{\n"
"\n"
"color:white;\n"
"border:none;\n"
" font-size:22px;\n"
" font-family:century gothic;\n"
"}")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(720, 380, 461, 431))
        self.frame_2.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"border-radius-left:15px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(210, 240, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pushButton.setStyleSheet("background:#333;\n"
"border:3px;\n"
"font-size:13px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(144, 370, 201, 41))
        self.pushButton_2.setStyleSheet("border-radius:15px;\n"
"background:red;\n"
"font-size:20px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 47, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(160, 75, 151, 21))
        self.label_3.setStyleSheet("background-color:white;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1335, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AGENDAMENTO DE VACINAÇÃO"))
        self.comboBox.setItemText(0, _translate("MainWindow", "AC"))
        self.comboBox.setItemText(1, _translate("MainWindow", "AL"))
        self.comboBox.setItemText(2, _translate("MainWindow", "AP"))
        self.comboBox.setItemText(3, _translate("MainWindow", "BA"))
        self.comboBox.setItemText(4, _translate("MainWindow", "CE"))
        self.comboBox.setItemText(5, _translate("MainWindow", "DF"))
        self.comboBox.setItemText(6, _translate("MainWindow", "ES"))
        self.comboBox.setItemText(7, _translate("MainWindow", "GO"))
        self.comboBox.setItemText(8, _translate("MainWindow", "MA"))
        self.comboBox.setItemText(9, _translate("MainWindow", "MT"))
        self.comboBox.setItemText(10, _translate("MainWindow", "MS"))
        self.comboBox.setItemText(11, _translate("MainWindow", "MG"))
        self.comboBox.setItemText(12, _translate("MainWindow", "PA"))
        self.comboBox.setItemText(13, _translate("MainWindow", "PB"))
        self.comboBox.setItemText(14, _translate("MainWindow", "PR"))
        self.comboBox.setItemText(15, _translate("MainWindow", "PE"))
        self.comboBox.setItemText(16, _translate("MainWindow", "PI"))
        self.comboBox.setItemText(17, _translate("MainWindow", "RJ"))
        self.comboBox.setItemText(18, _translate("MainWindow", "RN"))
        self.comboBox.setItemText(19, _translate("MainWindow", "RS"))
        self.comboBox.setItemText(20, _translate("MainWindow", "RO"))
        self.comboBox.setItemText(21, _translate("MainWindow", "RR"))
        self.comboBox.setItemText(22, _translate("MainWindow", "SC"))
        self.comboBox.setItemText(23, _translate("MainWindow", "SP"))
        self.comboBox.setItemText(24, _translate("MainWindow", "SE"))
        self.comboBox.setItemText(25, _translate("MainWindow", "TO"))
        self.pushButton.setText(_translate("MainWindow", "VOLTAR"))
        self.pushButton_2.setText(_translate("MainWindow", "AGENDAR"))
        self.label_2.setText(_translate("MainWindow", "Nome :"))
