# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\renne\Desktop\Python\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1640, 829)
        MainWindow.setStyleSheet("background-image: url(teste.jpg);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_login = QtWidgets.QFrame(self.centralwidget)
        self.frame_login.setGeometry(QtCore.QRect(720, 380, 461, 431))
        self.frame_login.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"}")
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.Push_Logar = QtWidgets.QPushButton(self.frame_login)
        self.Push_Logar.setGeometry(QtCore.QRect(70, 320, 311, 51))
        self.Push_Logar.setStyleSheet("border-radius:15px;\n"
"background:red;\n"
"font-size:20px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"")
        self.Push_Logar.setObjectName("Push_Logar")
        self.Login_usuario = QtWidgets.QLineEdit(self.frame_login)
        self.Login_usuario.setGeometry(QtCore.QRect(100, 120, 261, 41))
        self.Login_usuario.setStyleSheet("QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"color:white;\n"
"font-size:20px;\n"
"border-bottom:2px solid #717072;\n"
"}\n"
"QLineEdit:hover{\n"
"\n"
"\n"
"    border-bottom:2px solid rgb(212, 212, 212);\n"
"}\n"
"QLineEdit:pressed{\n"
"\n"
"\n"
"    border-bottom:2px solid rgb(212, 212, 212);\n"
"}")
        self.Login_usuario.setText("")
        self.Login_usuario.setMaxLength(11)
        self.Login_usuario.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Login_usuario.setObjectName("Login_usuario")
        self.Push_Voltar = QtWidgets.QPushButton(self.frame_login)
        self.Push_Voltar.setGeometry(QtCore.QRect(30, 30, 61, 51))
        self.Push_Voltar.setStyleSheet("QPushButton{\n"
"background:#333;\n"
"border:3px;\n"
"font-size:13px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:1px solid rgb(93, 93, 93)\n"
"\n"
"}")
        self.Push_Voltar.setObjectName("Push_Voltar")
        self.label_3 = QtWidgets.QLabel(self.frame_login)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.Push_Registrar = QtWidgets.QPushButton(self.frame_login)
        self.Push_Registrar.setGeometry(QtCore.QRect(180, 380, 75, 41))
        self.Push_Registrar.setStyleSheet("QPushButton{\n"
"background:#333;\n"
"border:3px;\n"
"font-size:13px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:1px solid rgb(93, 93, 93)\n"
"\n"
"}")
        self.Push_Registrar.setObjectName("Push_Registrar")
        self.Login_senha = QtWidgets.QLineEdit(self.frame_login)
        self.Login_senha.setGeometry(QtCore.QRect(100, 220, 261, 41))
        self.Login_senha.setStyleSheet("QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"color:white;\n"
"font-size:20px;\n"
"border-bottom:2px solid #717072;\n"
"}\n"
"QLineEdit:hover{\n"
"\n"
"\n"
"    border-bottom:2px solid rgb(212, 212, 212);\n"
"}\n"
"QLineEdit:pressed{\n"
"\n"
"\n"
"    border-bottom:2px solid rgb(212, 212, 212);\n"
"}")
        self.Login_senha.setText("")
        self.Login_senha.setMaxLength(8)
        self.Login_senha.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Login_senha.setObjectName("Login_senha")
        self.frame_login_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_login_2.setGeometry(QtCore.QRect(720, 290, 461, 91))
        self.frame_login_2.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"border-bottom:5px solid white;\n"
"\n"
"}")
        self.frame_login_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_2.setObjectName("frame_login_2")
        self.Text_Login = QtWidgets.QLabel(self.frame_login_2)
        self.Text_Login.setGeometry(QtCore.QRect(200, 28, 101, 41))
        self.Text_Login.setStyleSheet("*{\n"
"\n"
"color:white;\n"
"border:none;\n"
" font-size:22px;\n"
" font-family:century gothic;\n"
"}")
        self.Text_Login.setObjectName("Text_Login")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Push_Logar.setText(_translate("MainWindow", "Logar"))
        self.Login_usuario.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.Push_Voltar.setText(_translate("MainWindow", "VOLTAR"))
        self.Push_Registrar.setText(_translate("MainWindow", "REGISTRAR"))
        self.Login_senha.setPlaceholderText(_translate("MainWindow", "DATA DE NASCIMENTO"))
        self.Text_Login.setText(_translate("MainWindow", "LOGIN"))
