# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\renne\Desktop\Python\menu_agendamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 866)
        MainWindow.setStyleSheet("background-image: url(teste.jpg);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(840, 250, 361, 80))
        self.frame.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"border-bottom:5px solid white;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 30, 251, 31))
        self.label.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:none;\n"
" font-size:22px;\n"
" font-family:century gothic;\n"
"}")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(840, 330, 361, 371))
        self.frame_2.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_agendamento = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_agendamento.setGeometry(QtCore.QRect(40, 20, 281, 61))
        self.pushButton_agendamento.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background:rgb(70, 70, 70);\n"
"    font-size:20px;\n"
"    font-family:century gothic;\n"
"    color:white;\n"
"}\n"
"")
        self.pushButton_agendamento.setObjectName("pushButton_agendamento")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_logout.setGeometry(QtCore.QRect(140, 320, 75, 23))
        self.pushButton_logout.setStyleSheet("QPushButton{\n"
"background:#333;\n"
"border:3px;\n"
"font-size:13px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:1px solid rgb(93, 93, 93)\n"
"\n"
"}")
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 150, 351, 111))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(140, 280, 81, 23))
        self.pushButton.setStyleSheet("border-radius:15px;\n"
"background:green;\n"
"font-size:20px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 311, 51))
        self.label_2.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:none;\n"
" font-size:22px;\n"
" font-family:century gothic;\n"
"}")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MENU AGENDAMENTO"))
        self.pushButton_agendamento.setText(_translate("MainWindow", "AGENDAR VACINAÇÃO"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Estado"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cidade"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Endereco"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Data"))
        self.pushButton.setText(_translate("MainWindow", "Atualizar"))
        self.label_2.setText(_translate("MainWindow", "AGENDAMENTO CADASTRADO"))
