# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\renne\Desktop\Python\Tela_Inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 838)
        MainWindow.setStyleSheet("\n"
"QMainWindow{\n"
"    background-image: url(teste.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(840, 330, 361, 371))
        self.frame.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(90, 100, 181, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background:rgb(70, 70, 70);\n"
"    font-size:20px;\n"
"    font-family:century gothic;\n"
"    color:white;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 220, 181, 41))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius:15px;\n"
"    background:rgb(70, 70, 70);\n"
"    font-size:20px;\n"
"    font-family:century gothic;\n"
"    color:white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(840, 250, 361, 80))
        self.frame_2.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"border-bottom:5px solid white;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 151, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:none;\n"
" font-size:22px;\n"
" font-family:century gothic;\n"
"}")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "LOGAR"))
        self.pushButton_2.setText(_translate("MainWindow", "CADASTRAR"))
        self.label_2.setText(_translate("MainWindow", "MENU INICIAL"))
