# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\renne\Desktop\Python\Tela_vacinação.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 689)
        MainWindow.setStyleSheet("background-image: url(teste.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(320, 250, 621, 431))
        self.frame.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(150, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(150, 100, 47, 13))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 111, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:#333;\n"
"border:3px;\n"
"font-size:13px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:1px solid rgb(93, 93, 93)\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 370, 171, 41))
        self.pushButton_2.setStyleSheet("border-radius:15px;\n"
"background:red;\n"
"font-size:20px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_1.setGeometry(QtCore.QRect(200, 60, 281, 28))
        self.lineEdit_1.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:white;\n"
"font-size:20px;\n"
"border-bottom:2px solid #717072;")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setMaxLength(14)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 90, 281, 28))
        self.lineEdit_2.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:white;\n"
"font-size:20px;\n"
"border-bottom:2px solid #717072;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(16)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 120, 281, 28))
        self.lineEdit_3.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:white;\n"
"font-size:20px;\n"
"border-bottom:2px solid #717072;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(20)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(130, 250, 47, 13))
        self.label_7.setObjectName("label_7")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget.setGeometry(QtCore.QRect(180, 160, 331, 191))
        self.calendarWidget.setObjectName("calendarWidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(320, 150, 621, 101))
        self.frame_2.setStyleSheet("\n"
"QFrame{\n"
"background:#333;\n"
"\n"
"border-bottom:5px solid white;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(210, 30, 191, 41))
        self.label.setStyleSheet("*{\n"
"\n"
"color:white;\n"
"border:none;\n"
" font-size:22px;\n"
" font-family:century gothic;\n"
"}")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Estado"))
        self.label_3.setText(_translate("MainWindow", "Endereço"))
        self.label_5.setText(_translate("MainWindow", "Cidade"))
        self.pushButton.setText(_translate("MainWindow", "VOLTAR"))
        self.pushButton_2.setText(_translate("MainWindow", "AGENDAR"))
        self.lineEdit_1.setPlaceholderText(_translate("MainWindow", "ESTADO"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "CIDADE"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "ENDEREÇO"))
        self.label_7.setText(_translate("MainWindow", "Data"))
        self.label.setText(_translate("MainWindow", "Tela de vacinação"))
